name: Build and Push Docker Image to Docker Hub
on:
    push:
        branches:
            - main
        paths:
            - Dockerfile

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build Image
              run: docker build -t amongbagas/tellme-app:latest --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}
                  .
            - name: Log in to Docker Hub
              run: docker login -u amongbagas -p ${{ secrets.DOCKER_HUB_TOKEN }}
            - name: Push Image
              run: docker push amongbagas/tellme-app:latest
