name: Build and Push Docker Image to Docker Hub
on:
    push:
        branches:
            - main
        paths:
            - Dockerfile

jobs:
    runs-on:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build Image
              run: docker build -t amongbagas/tellme-app:latest .
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  NEXT_PUBLIC_WEBSOCKET_URL: ${{ secrets.NEXT_PUBLIC_WEBSOCKET_URL }}
                  BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
                  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
                  EMAIL_SENDER_NAME: ${{ secrets.EMAIL_SENDER_NAME }}
                  EMAIL_SENDER_ADDRESS: ${{ secrets.EMAIL_SENDER_ADDRESS }}
            - name: Log in to Docker Hub
              run: docker login -u amongbagas -p ${{ secrets.DOCKER_HUB_TOKEN }}
            - name: Push Image
              run: docker push amongbagas/tellme-app:latest
