name: Build and Push Docker Image to Docker Hub
on: [workflow_dispatch]

jobs:
    runs-on:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build Image
              run: |
                  # Inisialisasi variabel untuk argumen build
                  BUILD_ARGS=""
                  # Tambahkan setiap argumen build ke variabel
                  BUILD_ARGS+=" --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}"
                  BUILD_ARGS+=" --build-arg NEXT_PUBLIC_WEBSOCKET_URL=${{ secrets.NEXT_PUBLIC_WEBSOCKET_URL }}"
                  BUILD_ARGS+=" --build-arg BETTER_AUTH_URL=${{ secrets.BETTER_AUTH_URL }}"
                  BUILD_ARGS+=" --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
                  BUILD_ARGS+=" --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}"
                  BUILD_ARGS+=" --build-arg RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}"
                  BUILD_ARGS+=" --build-arg EMAIL_SENDER_NAME=${{ secrets.EMAIL_SENDER_NAME }}"
                  BUILD_ARGS+=" --build-arg EMAIL_SENDER_ADDRESS=${{ secrets.EMAIL_SENDER_ADDRESS }}"

                  # Jalankan perintah docker build dengan semua argumen yang terkumpul
                  docker build -t amongbagas/tellme-app:latest ${BUILD_ARGS} .

            - name: Log in to Docker Hub
              run: docker login -u amongbagas -p ${{ secrets.DOCKER_HUB_TOKEN }}
            - name: Push Image
              run: docker push amongbagas/tellme-app:latest
